### ISSUE TITLE
Typo @ Users management

### ISSUE THREAD

**Issue by abarberenaCPDS** [yoelhor/woodgrove-portal#1]
Hi Yoel, :wave:

Thanks for setting this demo website up, it has been incredible to learn more about it and familiarize with the product and its capabilities.

Just wanted to take a moment to let you know about typo I found while I was looking into it.

Thanks,

Abe

![image](https://github.com/yoelhor/woodgrove-portal/assets/43246964/bcfbd2eb-73aa-4fd2-97c5-e7f3da79190c)

**Comment by yoelhor** [comment]
Thank you @abarberenaCPDS for your feedback. I have fixed the typo with this commit https://github.com/yoelhor/woodgrove-portal/commit/c7b9c00c4a5554461b3fa5a19e7b9922e73be4a5
